version: '3.8'

services:
  app:
    build:
      context: .
    container_name: social-media-app
    env_file:
      - .env
    ports:
      - 3001:3000
    depends_on:
      - postgresql
      - rabbitmq
    environment:
      - NODE_ENV=production
      - DB_HOST=postgresql
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    networks:
      - social-media
    restart: unless-stopped

  consumer:
    build:
      context: .
    container_name: social-media-consumer
    command: 'pnpm start:consumer'
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    networks:
      - social-media
    restart: unless-stopped

  postgresql:
    container_name: postgresql
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - social-media
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - social-media
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  social-media:
    name: social-media
    driver: bridge

volumes:
  postgresql_data:
    name: social-media-db-data
  rabbitmq_data:
    name: social-media-rabbitmq-data
